# Setup
title:        Coolman
tagline:      TECHNICALLY-ORIENTED
baseurl:      "https://zhanglianxin.github.io"
paginate:     5

# About/contact
author:
  name:       zhanglianxin
  url:        //github.com/zhanglianxin/

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown
