# Setup
title:        Coolman
tagline:      TECHNICALLY-ORIENTED
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       zhanglianxin
  url:        //github.com/zhanglianxin/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
